/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gymsystem;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
       // StartPoint classUnderTest = new StartPoint();
        assertTrue(true, "someLibraryMethod should return 'true'");
    }
}
